# Site settings
title: CSW
email: your-email@domain.com
url: https://curlysemi.github.io/faketoshi
description: "The world's first token distributed via Proof of Fraud (PoF)! <br> Whitepaper coming soon!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Made with light-hearted contempt by <span class='curlysemi'>{;</span>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/faketoshi/

# Build settings
markdown: kramdown
permalink: pretty
